# Generated by Django 5.0.6 on 2024-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('link', models.URLField()),
                ('snippet', models.TextField()),
                ('publication_info', models.TextField()),
            ],
        ),
    ]
