# Generated by Django 5.0.6 on 2024-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicresult',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
